---
title: "Sesión 3: 06/09/2017"
output: html_notebook
---

### Interpretación Frecuentista de la Probabilidad
#### Frecuencias Relativas

```{r}
set.seed(175904)
lanzamientos_10 <- sample(c("A", "S"), 10, replace = TRUE)
lanzamientos_10
```

Suma acumulada
```{r}
cumsum(lanzamientos_10 == "A")
```

Frecuencias relativas de águilas
```{r}
cumsum(lanzamientos_10 == "A") / 1:10
```

```{r}
cummean(lanzamientos_10 == "A")
```
###_Ley empírica de los promedios_

De 1 a 1000 ensayos
```{r}
n <- 1000
lanzamientos_1000 <- data_frame(num_lanzamiento = 1:n, lanzamiento = sample(c("A", "S"), n, replace = TRUE)) %>%
    mutate(frec_rel = cummean(lanzamiento == "A")) 
ggplot(data = lanzamientos_1000, aes(x = num_lanzamiento, y = frec_rel)) +
  geom_hline(yintercept = 0.5, color = "red", alpha = 0.5) +
  geom_line(color = "darkgray") +
  geom_point(size = 1.0) +
  labs(y = "frecuencia relativa", title = "1000 volados", x = "lanzamiento")
```

Ejemplo 2: freq relativas de águilas para 3 series de 1000

```{r}
lanzar <- function(n = 1000){
    data_frame(num_lanzamiento = 1:n, lanzamiento = sample(c("A", "S"), n, replace = TRUE)) %>% 
        mutate(frec_rel = cummean(lanzamiento == "A"))
  }
head(lanzar())
#> # A tibble: 6 x 3
#>   num_lanzamiento lanzamiento frec_rel
#>             <int>       <chr>    <dbl>
#> 1               1           S     0.00
#> 2               2           A     0.50
#> 3               3           A     0.67
#> 4               4           S     0.50
#> 5               5           S     0.40
#> 6               6           S     0.33

set.seed(175904)
# usamos la función map_df del paquete purrr
map_df(1:3, ~lanzar(), .id = "serie") %>% 
    ggplot(aes(x = log(num_lanzamiento), y = frec_rel, color = as.character(serie))) +
        geom_hline(yintercept = 0.5, color = "darkgray") + 
        geom_line() +
        scale_x_continuous("lanzamiento", labels = exp, 
            breaks = log(sapply(0:10, function(i) 2 ^ i))) +
        labs(color = "serie", y = "frecuencia relativa", title = "1000 volados")

```

Ejemplo 3: freq realtiva de AA para 10,000 lanzamientos

```{r}
n <- 10000
moneda_1 <- sample(c("A", "S"), n, replace = TRUE)
moneda_2 <- sample(c("A", "S"), n, replace = TRUE)
sum(moneda_1 == moneda_2 & moneda_1 == "A") / n
```

### Simulación para el cálculo de probabilidades

_La ruina del jugador_
```{r}
apostar <- function(dinero = 100, apuesta = 5, tope = 200, p = 0.47){
    while(0 < dinero & dinero < tope) {
        if(runif(1) < p) { #Genera un valor random con distribución uniforme
            dinero <- dinero + apuesta
        } else {
            dinero <- dinero - apuesta
        }
    }
    dinero > 0
}
n_juegos <- 5000
juegos <- rerun(n_juegos, apostar(apuesta = 5)) %>% flatten_dbl()
mean(juegos)
#> [1] 0.0802

juegos <- rerun(n_juegos, apostar(apuesta = 100)) %>% flatten_dbl()
mean(juegos)
#> [1] 0.4636
```

